CREATE TABLE BankCustomers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100),
    Age INT,
    LocationID INT,
    JoinedBank DATE,
    BankingContact VARCHAR(100),
    Nationality VARCHAR(50),
    Occupation VARCHAR(100),
    FeeStructure VARCHAR(20),
    LoyaltyClassification VARCHAR(20),
    EstimatedIncome DECIMAL(15,2),
    SuperannuationSavings DECIMAL(15,2),
    CreditCardCount INT,
    CreditCardBalance DECIMAL(15,2),
    BankLoans DECIMAL(15,2),
    BankDeposits DECIMAL(15,2),
    CheckingAccounts DECIMAL(15,2),
    SavingAccounts DECIMAL(15,2),
    ForeignCurrencyAccount DECIMAL(15,2),
    BusinessLending DECIMAL(15,2),
    PropertiesOwned INT,
    RiskWeighting INT,
    BRId INT,
    GenderId INT,
    IAId INT
);
